### ISSUE TITLE
cannons 2.4.8 firing not working for custom cannons

### ISSUE THREAD

**Issue by nitro77live** [DerPavlov/Cannons#16]
there are no errors in the logs for this but for some of my custom cannons i set the firing mechanism to a button but when i load the cannon  it does not fire after i push the button. it works for one cannons but all the others dont work i am using the version 1.12.2

**Comment by DerPavlov** [comment]
Can you send me the design, I will have a look.

**Comment by nitro77live** [comment]
[cannons.zip](https://github.com/DerPavlov/Cannons/files/2994290/cannons.zip)

**Comment by nitro77live** [comment]
this is the file for the 2 non working cannons

**Comment by DerPavlov** [comment]
I renamed your designs to 
20mmcannon.schematic and 20mmcannon.yml
10inchgun.schematic and 10inchgun.yml

For the 10inchgun I replaced this section:
```
  redstoneTrigger: 
    #the block used by the schematic to indicate where the redstone signal needs to lead to. Default is a lever
    schematic: 'STONE_BUTTON:4'
    #the block used in game where the redstone signal needs to lead to. Default is stone button
    ingame: 'STONE_BUTTON:4'

```

The 20mmcannon was facing west,  and I had to set this section to
```
redstoneTrigger: 
    #the block used by the schematic to indicate where the redstone signal needs to lead to. Default is a lever
    schematic: 'STONE_BUTTON:2'
    #the block used in game where the redstone signal needs to lead to. Default is stone button
    ingame: 'STONE_BUTTON:2'
```

Sadly there is no plugin which could help me, so I had to check with F3 and the wiki to get the correct datavalue. Cannons 2.5 comes with a blockdata command.
I recommend building your cannons in the same direction to avoid these copy paste issues.
Cannons can be spawned for testing purposes with '/cannons create 20mmcannon'

Let me know if this worked for you.
