### ISSUE TITLE
Can't get named projectiles to work on 1.15 similar to how they worked on 1.12.2

### ISSUE THREAD

**Issue by wolfebersahd** [DerPavlov/Cannons#25]
1. Create a projectiles on 1.12.2
```yaml
#(minimum is id:data. Named items id:data:displayName:lore1:lore2:....)
  loadingItem: '397:3:Cannonball'
```
2. Try the same with 1.15.2
```yaml
#(minimum is id:data. Named items id:data:displayName:lore1:lore2:....)
  loadingItem: 'player_head:-1:Cannonball'
```

1.15 doesn't have data anymore so it's not working.
Regular `player_head`s work fine but adding a name check to it doesn't i tried
```yaml
#(minimum is id:data. Named items id:data:displayName:lore1:lore2:....)
  loadingItem: 'player_head:-1:Cannonball'
  loadingItem: 'player_head::Cannonball'
  loadingItem: 'player_head:Cannonball'
  loadingItem: 'minecraft:player_head:-1:Cannonball'
  loadingItem: 'minecraft:player_head::Cannonball'
  loadingItem: 'minecraft:player_head:Cannonball'
```
I don't know what to do to get named projectiles to work on 1.15 now.
